version: '2'
services:
    jhipmongo-app:
        image: jhipmongo
        external_links:
            - jhipmongo-mongodb:mongodb
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=jhipmongo
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    jhipmongo-mongodb:
        extends:
            file: mongodb.yml
            service: jhipmongo-mongodb
