version: '2'
services:
    jhipmongo-mongodb:
        container_name: jhipmongo-mongodb
        image: mongo:3.3.12
        ports:
            - "27017:27017"
        # volumes:
        #     - ~/volumes/jhipster/jhipmongo/mongodb/:/data/db/
